use_frameworks!

target 'CalculatorPP_Example' do
  pod 'CalculatorPP', :path => '../'

  target 'CalculatorPP_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
